# Generated by Django 4.2.20 on 2025-08-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_high_threshold', models.PositiveIntegerField(default=60)),
                ('flash_color_a', models.CharField(default='#ffffff', max_length=7)),
                ('flash_color_b', models.CharField(default='#b91c1c', max_length=7)),
                ('flash_opacity', models.FloatField(default=0.35)),
                ('flash_speed_ms', models.PositiveIntegerField(default=700)),
                ('flash_total_ms', models.PositiveIntegerField(default=12000)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('sound_normal_file', models.FileField(blank=True, null=True, upload_to='sounds/')),
                ('sound_normal_volume', models.FloatField(default=0.55)),
                ('sound_normal_repeat_ms', models.PositiveIntegerField(default=0)),
                ('sound_normal_max_ms', models.PositiveIntegerField(default=4000)),
                ('sound_high_file', models.FileField(blank=True, null=True, upload_to='sounds/')),
                ('sound_high_volume', models.FloatField(default=0.75)),
                ('sound_high_repeat_ms', models.PositiveIntegerField(default=1500)),
                ('sound_high_max_ms', models.PositiveIntegerField(default=10000)),
                ('banner_title', models.CharField(default='⚠️ Real-Time Threat Alert', max_length=200)),
                ('template_normal', models.TextField(default='{user} triggered anomaly with score {score_pct}% — {reason}')),
                ('template_high', models.TextField(default='🚨 {user} triggered HIGH anomaly ({score_pct}%) — {reason}')),
                ('date_format', models.CharField(default='YYYY-MM-DD HH:mm', max_length=32)),
                ('max_lines', models.PositiveIntegerField(default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
