# Generated by Django 4.2.20 on 2025-08-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimesettings',
            name='sound_high_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='realtimesettings',
            name='sound_normal_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
