# Generated by Django 4.2.20 on 2025-05-14 03:10

from django.db import migrations
import hashlib

def create_admin_user(apps, schema_editor):
    CustomUser = apps.get_model('ThreatDetection', 'CustomUser')
    if not CustomUser.objects.filter(username='admin').exists():
        admin = CustomUser(
            username='admin',
            department='Security',
            role='admin',
            is_suspended=False
        )
        admin.password_hash = hashlib.sha256('admin123'.encode()).hexdigest()
        admin.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ThreatDetection', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin_user),
    ]
