# Generated by Django 4.2.20 on 2025-07-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThreatDetection', '0002_seed_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_token',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
