# Generated by Django 4.2.20 on 2025-07-25 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThreatDetection', '0003_customuser_auth_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='auth_token',
        ),
    ]
