# Generated by Django 4.2.20 on 2025-08-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThreatDetection', '0006_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
