# Generated by Django 4.2.20 on 2025-08-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThreatDetection', '0007_alerts_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
