# Generated by Django 4.2.20 on 2025-08-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThreatDetection', '0008_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
