# Generated by Django 4.2.20 on 2025-08-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThreatDetection', '0009_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
