# Generated by Django 4.2.20 on 2025-08-11 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ThreatDetection', '0012_customuser_address_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hybrid_daily', max_length=100, unique=True)),
                ('bundle_path', models.CharField(max_length=255)),
                ('high_threshold', models.FloatField(default=0.95)),
                ('alert_rate', models.FloatField(default=0.001)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CohortBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_role', models.CharField(blank=True, db_index=True, max_length=50)),
                ('cohort_department', models.CharField(blank=True, db_index=True, max_length=100)),
                ('feature_name', models.CharField(db_index=True, max_length=100)),
                ('median', models.FloatField(default=0.0)),
                ('mad', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('cohort_role', 'cohort_department', 'feature_name')},
            },
        ),
        migrations.CreateModel(
            name='UserDailyAgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('number_of_emails_dispatched', models.IntegerField(default=0)),
                ('number_of_files_interacted', models.IntegerField(default=0)),
                ('total_logon_attempts', models.IntegerField(default=0)),
                ('usb_connection_incidents', models.IntegerField(default=0)),
                ('nighttime_email_events', models.IntegerField(default=0)),
                ('number_of_night_logons', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'day')},
            },
        ),
    ]
