# Generated by Django 4.2.20 on 2025-08-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThreatDetection', '0013_modelconfig_cohortbaseline_userdailyagg'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortbaseline',
            name='mean_14d',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cohortbaseline',
            name='mean_30d',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cohortbaseline',
            name='mean_7d',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cohortbaseline',
            name='std_14d',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cohortbaseline',
            name='std_30d',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cohortbaseline',
            name='std_7d',
            field=models.FloatField(default=0.0),
        ),
    ]
