# Generated by Django 4.2.20 on 2025-08-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThreatDetection', '0014_cohortbaseline_mean_14d_cohortbaseline_mean_30d_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelconfig',
            name='high_threshold',
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='decision_threshold',
            field=models.FloatField(default=0.9),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='name',
            field=models.CharField(default='daily_xgb', max_length=100, unique=True),
        ),
    ]
