"""
Django settings for Dissertation project.

Generated by 'django-admin startproject' using Django 4.2.20.
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

# SECURITY
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'True') == 'True'
ALLOWED_HOSTS = [h for h in os.getenv("ALLOWED_HOSTS", "").split(",") if h]

# Auth redirects
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'

# ---------------------------------------------------------------------
# Applications
# ---------------------------------------------------------------------
INSTALLED_APPS = [
    # 'django.contrib.admin',  # enable if you use Django admin
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'rest_framework',
    'channels',

    # your apps
    "ThreatDetection.apps.ThreatDetectionConfig",
    "src.alerts.apps.AlertsConfig",
    'src.dashboard',
    'src.logs',
    'src.mlengine',
    'src.users.apps.UsersConfig',  # ensure AppConfig runs (signals/ready)
]

USE_TZ = True
TIME_ZONE = 'Asia/Kathmandu'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'ThreatDetection.authentication.CustomTokenAuthentication',
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    'DEFAULT_PERMISSION_CLASSES': [],
}

SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("Bearer",),
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

AUTH_USER_MODEL = 'ThreatDetection.CustomUser'

ASGI_APPLICATION = 'Dissertation.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": ["redis://127.0.0.1:6379/0"]},
    }
}

MEDIA_URL  = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

JWT_SECRET = os.getenv("JWT_SECRET", SECRET_KEY)
JWT_ALGORITHM = "HS256"

# ---------------------------------------------------------------------
# Middleware
# ---------------------------------------------------------------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS
# robust split that ignores empty entries
CORS_ALLOWED_ORIGINS = [o for o in os.getenv("CORS_ALLOWED_ORIGINS", "").split(",") if o]

ROOT_URLCONF = 'Dissertation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Dissertation.wsgi.application'

# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT", "5432"),
        # Make sure we operate in the 'public' schema where core tables live
        'OPTIONS': {'options': '-c search_path=public'},
    }
}

# Internationalization
LANGUAGE_CODE = 'en-us'
USE_I18N = True

# Static files
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
SIGNUP_ACTIVATION_TIMEOUT_SECONDS = int(os.getenv("SIGNUP_ACTIVATION_TIMEOUT_SECONDS", "3600"))
PASSWORD_RESET_TIMEOUT = SIGNUP_ACTIVATION_TIMEOUT_SECONDS

# Celery
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = "redis://localhost:6379/1"
CELERY_WORKER_POOL = "solo"

SECURITY_NOTIFICATION_EMAILS = [
    e.strip() for e in os.getenv('SECURITY_NOTIFICATION_EMAILS', '').split(',')
    if e.strip()
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]



# """
# Django settings for Dissertation project.
#
# Generated by 'django-admin startproject' using Django 4.2.20.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/4.2/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/4.2/ref/settings/
# """
#
# from pathlib import Path
# import os
# from dotenv import load_dotenv
# from pathlib import Path
#
# BASE_DIR = Path(__file__).resolve().parent.parent
# load_dotenv(BASE_DIR / '.env')
#
#
#
# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# # Build paths inside the project like this: BASE_DIR / 'subdir'.
#
#
# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/
#
# # SECURITY WARNING: keep the secret key used in production secret!
# # SECRET_KEY = 'django-insecure-%39aan&*bgi0eu8hvkmq_8l1qf51qubh3ixb*ufqh=6^dd()4x'
# SECRET_KEY = os.getenv('SECRET_KEY')
#
# # SECURITY WARNING: don't run with debug turned on in production!
#
# DEBUG = os.getenv('DEBUG', 'True') == 'True'
#
#
# ALLOWED_HOSTS = [h for h in os.getenv("ALLOWED_HOSTS", "").split(",") if h]
#
# # Authentication settings
# LOGIN_URL = '/login/'
# LOGIN_REDIRECT_URL = '/'
#
# # Application definition
#
# INSTALLED_APPS = [
#     # 'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     "ThreatDetection.apps.ThreatDetectionConfig",
#     'django.contrib.staticfiles',
#     "src.alerts.apps.AlertsConfig",
#     'django.contrib.messages',
#     # 'django.contrib.staticfiles',
#     'corsheaders',
#
#
#     # 'ThreatDetection',
#     'rest_framework',
#     'channels',
#     'src.dashboard',
#     'src.logs',
#     # 'src.alerts',
#     'src.mlengine',
#     'src.users'
#
# ]
#
# USE_TZ = True
# TIME_ZONE = 'Asia/Kathmandu'
#
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'ThreatDetection.authentication.CustomTokenAuthentication',
#         "rest_framework_simplejwt.authentication.JWTAuthentication",
#     ],
#     'DEFAULT_PERMISSION_CLASSES': [],
# }
#
# from datetime import timedelta
# SIMPLE_JWT = {
#     "AUTH_HEADER_TYPES": ("Bearer",),
#     "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
#     "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
# }
#
# AUTH_USER_MODEL = 'ThreatDetection.CustomUser'
#
# ASGI_APPLICATION = 'Dissertation.asgi.application'
#
#
#
#
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {"hosts": ["redis://127.0.0.1:6379/0"]},
#     }
# }
#
# MEDIA_URL  = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"
#
# JWT_SECRET = os.getenv("JWT_SECRET", SECRET_KEY)
# JWT_ALGORITHM = "HS256"
#
#
#
# MIDDLEWARE = [
#     'corsheaders.middleware.CorsMiddleware',
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]
#
# # CORS_ALLOWED_ORIGINS = [
# #     "http://localhost:3000",
# # ]
# CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")
#
#
# ROOT_URLCONF = 'Dissertation.urls'
#
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / 'templates'],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]
#
# WSGI_APPLICATION = 'Dissertation.wsgi.application'
#
#
#
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv("DB_NAME"),
#         'USER': os.getenv("DB_USER"),
#         'PASSWORD': os.getenv("DB_PASSWORD"),
#         'HOST': os.getenv("DB_HOST"),
#         'PORT': os.getenv("DB_PORT", "5432"),
#         'OPTIONS': { 'options': '-c search_path=public' },
#     }
# }
#
#
#
#
#
# # Internationalization
# # https://docs.djangoproject.com/en/4.2/topics/i18n/
#
# LANGUAGE_CODE = 'en-us'
#
# # TIME_ZONE = 'UTC'
#
# USE_I18N = True
#
# # USE_TZ = True
#
#
# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/4.2/howto/static-files/
#
# STATIC_URL = '/static/'
# STATICFILES_DIRS = [BASE_DIR / 'static']
# # STATICFILES_DIRS = [
# #     BASE_DIR / "ThreatDetection/static",
# # ]
# STATIC_ROOT = BASE_DIR / 'staticfiles'
# # Default primary key field type
# # https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
#
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#
#
# EMAIL_HOST = os.getenv('EMAIL_HOST')
# EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
# EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
# EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
# DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
# SIGNUP_ACTIVATION_TIMEOUT_SECONDS = int(os.getenv("SIGNUP_ACTIVATION_TIMEOUT_SECONDS", "3600"))
# PASSWORD_RESET_TIMEOUT = SIGNUP_ACTIVATION_TIMEOUT_SECONDS
#
# CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
#
# # optional result backend
# CELERY_RESULT_BACKEND = "redis://localhost:6379/1"
#
# CELERY_WORKER_POOL = "solo"
#
# SECURITY_NOTIFICATION_EMAILS = [
#     e.strip() for e in os.getenv('SECURITY_NOTIFICATION_EMAILS', '').split(',')
#     if e.strip()
# ]
# CSRF_TRUSTED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
#
#     "http://localhost:5173",
#     "http://127.0.0.1:5173",
# ]